### get all

GET  http://localhost:8080/api/courses?page=0&size=3
### get by ids
GET  http://localhost:8080/api/courses/5

### get by name
GET  http://localhost:8080/api/courses/search?name=a&page=0&size=4

### get students by course id

GET  http://localhost:8080/api/courses/2/students
### create

POST  http://localhost:8080/api/courses
Content-Type: application/json

{
    "name": "Rust for Hacking Extreme",
    "description": "Rust programming language for hacking",
    "capacity":1,
    "active":true

}


###

PUT http://localhost:8080/api/courses/1
Content-Type: application/json

{
    "name": "Java Basics",
    "description": "Java for begginers",
    "capacity":20,
    "active":true

}

### 
DELETE http://localhost:8080/api/courses/6


