### get all
GET  http://localhost:8080/api/enrollments
### get by ids
GET  http://localhost:8080/api/enrollments/18

### save
POST http://localhost:8080/api/enrollments
Content-Type: application/json

{
  "courseId":4,
  "studentId":2
}
### update
PUT http://localhost:8080/api/enrollments/18
Content-Type: application/json

{
    "status": "CANCELLED",
    "courseId":4,
    "studentId":2

}


### delete
DELETE http://localhost:8080/api/enrollments/6