
GET  http://localhost:8080/api/enrollments
### get all
GET  http://localhost:8080/api/enrollments?page=1&size=4
### get by ids
GET  http://localhost:8080/api/enrollments/34

### get by student id
GET  http://localhost:8080/api/enrollments/student?studentId=9&page=0&size=3
### get by course id
GET  http://localhost:8080/api/enrollments/course?courseId=15&page=0&size=2
### GET BY STATUS
GET  http://localhost:8080/api/enrollments/status?status=COMPLETED&page=0&size=2
### save
POST http://localhost:8080/api/enrollments
Content-Type: application/json

{
  "courseId":15,
  "studentId":9
}
### update
PUT http://localhost:8080/api/enrollments/36
Content-Type: application/json

{
    "status": "CANCELLED",
    "courseId":15,
    "studentId":9

}


### delete
DELETE http://localhost:8080/api/enrollments/30