### get all

GET  http://localhost:8080/api/students

### get by id
GET  http://localhost:8080/api/students/2

### get by name
GET  http://localhost:8080/api/students/search?name=Ana

### get active

GET  http://localhost:8080/api/students/active

### get courses by student id

GET   http://localhost:8080/api/students/5/courses
### create

POST  http://localhost:8080/api/students
Content-Type: application/json

{
    "name": "John Doe 3",
    "email":"john.do3e@example.com",
    "active":true
}


###

PUT http://localhost:8080/api/students/8
Content-Type: application/json

{
    "name": "Ana Torres",
    "email":"ana.torre1s@example.com",
    "active":true
}

### 
DELETE http://localhost:8080/api/students/6


