GET  http://localhost:8080/api/students


### get all
GET  http://localhost:8080/api/students?page=2&size=2

### get by id
GET  http://localhost:8080/api/students/9

### get by name
GET  http://localhost:8080/api/students/search?name=Ana&page=1&size=1

### get courses by student id

GET   http://localhost:8080/api/students/4/courses?page=1&size=2
### create

POST  http://localhost:8080/api/students
Content-Type: application/json

{
    "name": "Pepito Perez8",
    "email":"pepito8@example.com"    
}


###

PUT http://localhost:8080/api/students/17
Content-Type: application/json

{
    "name": "Pepito Perez Updated",
    "email":"upd1atepp@example.com",
    "active":true
}
###


PUT http://localhost:8080/api/students/9/status?active=false
### 
DELETE http://localhost:8080/api/students/17


