//ONLY ADMIN CAN ACCESS THIS ENDPOINT
//Authorization: Basic YWRtaW46YWRtaW4=
GET  http://localhost:8080/api/users/customer
Authorization: Basic Y3VzdG9tZXI6Y3VzdG9tZXI=    
//customer denied


####
POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Basic Y3VzdG9tZXI6Y3VzdG9tZXI=

{
    "username":"Pepelepe1",
    "password":"pepe",
    "roles": "ROLE_ADMIN"

}